### ISSUE TITLE
FDMDS Improvements/Bugs

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#114]
**Describe the solution you'd like**
If you edit a request, the requested-user changes to the one who edited the request
Maybe only change the edit message from “edited” to "edited by USER" 

Display the requested user in Message like:
> " Einen Wunderschönen hier ist [ User Name von der Person, die die Frage eingesendet hat] , :slimewave: 
Heute würde ich gerne,.... und so weiter.

If you edit the Question the bots add again " heute möchte ich gerne..." so it appears twice because in modal this phrase is also

**ToDos**
- [x] Do not change the footer during editing
- [x] Display requested user
- [ ] fix question after edit
