### ISSUE TITLE
Team management (Meetings)

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#121]
**Is your feature request related to a problem? Please describe.**
Manage Meetings and ToDos

**Describe the solution you'd like**
- Plan Meeting via Bot (Create Discord Event with Meeting Channel as location)
- unsubscribe from a meeting (maybe several at once) [Reason optional?]
- All Member with Staff role will be listed in the Embed
- Member who unsubscribed from a Meeting will be listed in a other section
- A Member can also be late
- Set a Agenda for a meeting displayed in the Embed as well (Button "Add Agenda-Point" ?)
- At the end of a Meeting, the Agenda-Points can be Switch to a ToDo-Point

- what maybe also be a nice feature for meetings would be, if you could raise your hand, and then it adds 🖐 to the nickname

**ToDos**
- [x] Plan/Set Meeting via Bot
- [x] create Scheduled Event
- [ ] ~~Mention/Remind Staff Team 15 min before Meeting~~ (Already done via scheduled events I think)
- [x] unsubscribe from a meeting
- [x] list staff member in embed
- [x] list unsubscribed staff member
- [ ] a "to late" button
- [x] Agenda
  - [x] set
  - [x] remove
  - [x] Convert to ToDo
  - [x] Edit
  - [x] Add multiple
  - [x] Markdown enumeration
- [x] ToDo
  - [x] set Assignees
  - [x] change status to Done
- [ ] ~~rise Hand command~~ (If this is really required we should probably use a stage channel)
- [x] Add timestamp to content

**Additional context**
just a list of things that came to my mind about this topic...
does not have to be implemented exactly like this ;)
