### ISSUE TITLE
Ticket System

### ISSUE THREAD

**Issue by cyklon73** [SlimeCloud/java-SlimeBot#162]
Ticket system to replace the ticket bot

**ToDos**
- [ ] UI to create tickets
- [ ] set staff to claim tickets
- [ ] ticket claims so that the person who takes care of the ticket can claim it
- [ ] transcript after close 
- [ ] notify user after close in dm
- [ ] button to close with reason
- [ ] block chat for the user after closing
- [ ] command to add members to the ticket
- [ ] button to reopen a ticket
- [ ] button to delete a closed ticket

**Comment by MatitoDev** [comment]
- blacklist
- closerequest maybe also by users but then the staff should set the reason
- closeing should only be able by the staff 
- private thread for staff notes/discussions
- a way to reopen del tickets? the transcript is saved so it should be not that complicated
- limit max tickets per user
- open ticket for a user if the team seeks dialogue with a user
- for opening a ticket, a dropdown with Topics?
