### ISSUE TITLE
More Logs

### ISSUE THREAD

**Issue by MatitoDev** [SlimeCloud/java-SlimeBot#224]
Add some more logging, for some more information what's going on at the moment.

**ToDos**
`con` if it should be logged in Console
`cha` if it should be logged in to the Channel
- [ ] Log Config changes `con` `cha`
- [ ] Log alerts standardized (either always when checked (like spotify) or only when something is found) `con`
- [ ] Log new Birthday entries `con` (`cha`?)
- [ ] Log Card edits `con` (for better moderation options if necessary)
- [ ] Log AutoDeleteEvent `con` `chan`
- [ ] Log Quote del `con`
- [ ] Log Report Closed `con` `chan`

maybe we should add a system so split this in multiple Channels
