### ISSUE TITLE
New XP System

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#65]
**Is your feature request related to a problem? Please describe.**
You don't get XP in Voice Channels with Mee6

**Describe the solution you'd like**
New System

**ToDos**
- [ ] get old XP from mee6 API `https://mee6.xyz/api/plugins/levels/leaderboard/1077255218728796192?limit=1000&page=0` (once)
- [ ] leveling while writing (messages)
  - [ ] antispam
- [ ] leveling while talking (voice channel)
  -  Don't leveling when:
  - [ ] alone in channel
  - [ ] muted 
  - [ ] deaf
  - [ ] only one who are not muted

**Additional context**
A diagram like this would be nice.
Maybe useful API for this: https://quickchart.io/
![image](https://github.com/SlimeCloud/java-SlimeBot/assets/77804268/653abb9e-7236-409b-8c40-b679b6249fc8)
