### ISSUE TITLE
Replace Mee6

### ISSUE THREAD

**Issue by MatitoDA** [SlimeCloud/java-SlimeBot#92]
**Is your feature request related to a problem? Please describe.**
We all know mee6 is shit, so let's replace him. 

**Describe the solution you'd like**
We write our own system

**ToDos**
A list oft Features we are using from the Mee6 Bot
- [ ] Create Threads for every message in #Galerie 
- [ ] Welcome and Goodbye Message
- [ ] Create custom Commands or take over the current
- [ ] Automod
  - [ ] Bad words
  - [ ] Excessive spoilers
  - [ ] Caps
- [ ] Statistic Channel
  - [ ]  Member count
  - [ ] Role member count (Rat, live now)
- [ ] YouTube notification
- [ ] level system
- [ ] Birthdays (only if we can adopt the current data )

**Additional context**
Please do not create a PR for this hole “project”. Create PR only for single ToDos

**Comment by MineKing9534** [comment]
The automod part can be done via discord automod and regex
